---
title: Exploring NYC Flight Data
output: github_document
---

# Ways to charcterize typical delay characteristics of a group of flights


A flight is 15 minutes early 50% of the time, and 15 minutes late 50% of the time.

A flight is always 10 minutes late.

A flight is 30 minutes early 50% of the time, and 30 minutes late 50% of the time.

99% of the time a flight is on time. 1% of the time it's 2 hours late.

```{r}
library(nycflights13)
library(dplyr)

flights <- flights

# Delays by carrier

flights %>%
  group_by(carrier) %>%
  filter(is.na(dep_delay)) %>%
  summarise(n())

# Delays by originating airport
flights %>%
  group_by(origin) %>%
  filter(is.na(dep_delay)) %>%
  summarise(n())


# Number of flights by carrier to a destination
flights %>%
  group_by(carrier, dest) %>%
  summarise(n())

# Count of Uncancelled flights sorted by destination
flights %>%
  filter(!is.na(dep_delay)) %>%
  group_by(dest) %>%
  summarise(n())
  

# Cancelled flights by tailnum weighted by distance travelled, without count()
flights %>%
  filter(!is.na(dep_delay)) %>%
  group_by(tailnum, distance) %>% 
  summarise(n()) %>% 
  summarise(n() * sum(distance))

# Cancelled flights by tailnum weighted by distance travelled, using count()
flights %>%
  filter(!is.na(dep_delay)) %>%
  count(tailnum, wt = distance)
```


#Number of cancelled flights per day
```{r}

library(nycflights13)
library(dplyr)

# Calculate proportion of cancelled flights and avergae delay
cancelled_vs_delay <-  flights %>% 
  group_by(year, month, day) %>% 
  summarise(avg_delay = mean(dep_delay, na.rm = TRUE), # Calcylate mean dep_delay
            prop_cancelled = sum(is.na(dep_delay)) / n()) # number of cancelled flights / number of total flights

# plot it
library(ggplot2)

scatter1 <- ggplot(data=cancelled_vs_delay, aes(x=avg_delay, y= prop_cancelled)) +
  geom_point(aes(color=month)) + geom_smooth(method = 'loess', se=TRUE) +
  scale_color_gradientn(colors = terrain.colors(12)) +
  ggtitle('Proportion of cancelled flights vs Average Departure Delays for flights in 
NYC 2013')

scatter1

```


# Grouped Mutates & Filters
```{r}
# Which plane (tailnum) has worst on-time record
flights %>% 
  slice(which.min(dep_delay)) %>% # Get row with the minimum departure delay
  select(tailnum)


# Gets minimum departure delay for every day
flights %>% 
  group_by(year, month, day) %>% 
  slice(which.min(dep_delay))


# What time of day should you fly if you want to avoid delays as much as possible?
flights %>%
  group_by(year, month, day) %>% 
  summarise(mean=mean(dep_delay, na.rm=TRUE)) 
  # filter(dep_delay == min(dep_delay)) 
  # %>% 
  # group_by(dep_time) %>% 
  # summarise(n=n())


# For each destination, compute the total minutes of delay. For each flight, compute the proportion of the total delay for its destination.
flights %>% 
  group_by(dest) %>% 
  summarise(total_delay = sum(dep_delay, arr_delay, na.rm=TRUE)) %>% 
  mutate(prop_delay = total_delay / sum(total_delay))


# 
# Delays are typically temporally correlated: even once the problem that caused the initial delay has been resolved, later flights are delayed to allow earlier flights to leave. Using lag(), explore how the delay of a flight is related to the delay of the immediately preceding flight.


# Look at each destination. Can you find flights that are suspiciously fast? (i.e. flights that represent a potential data entry error). Compute the air time a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?

# Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.

# For each plane, count the number of flights before the first delay of greater than 1 hour.



  


```

